### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by PAWAN1SINGH** [nodejitsu/node-http-proxy#1028]
Express
500 TypeError: Cannot read property 'split' of undefined
at exports.authenticate (C:\salesforce\df14demo-master\routes\index.js:27:43)
at callbacks (C:\salesforce\df14demo-master\node_modules\express\lib\router\index.js:164:37)
at param (C:\salesforce\df14demo-master\node_modules\express\lib\router\index.js:138:11)
at pass (C:\salesforce\df14demo-master\node_modules\express\lib\router\index.js:145:5)
at Router._dispatch (C:\salesforce\df14demo-master\node_modules\express\lib\router\index.js:173:5)
at Object.router (C:\salesforce\df14demo-master\node_modules\express\lib\router\index.js:33:10)
at next (C:\salesforce\df14demo-master\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Immediate. (C:\salesforce\df14demo-master\node_modules\express-session\index.js:432:7)
at Immediate.immediate._onImmediate (timers.js:590:18)
at tryOnImmediate (timers.js:543:15)

**Comment by jcrugzz** [comment]
This does not seem to have anything to do with `http-proxy`. It look like the error comes from your `routes/index.js` file as shown in the stacktrace.

**Comment by steffanhalv** [comment]
@jcrugzz Are you sure?

I have the same error when enabling changeOrigin, but doesn't have it when disabled:

```js
TypeError: Cannot read property 'split' of undefined
    at required (/home/webservice/host/node_modules/requires-port/index.js:13:23)
    at Object.common.setupOutgoing (/home/webservice/host/node_modules/http-proxy/lib/http-proxy/common.js:101:7)
    at Array.stream (/home/webservice/host/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/home/webservice/host/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at /home/webservice/host/dist/index.js:47:12
    at Layer.handle [as handle_request] (/home/webservice/host/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/webservice/host/node_modules/express/lib/router/route.js:137:13)
    at next (/home/webservice/host/node_modules/express/lib/router/route.js:131:14)
    at next (/home/webservice/host/node_modules/express/lib/router/route.js:131:14)
    at next (/home/webservice/host/node_modules/express/lib/router/route.js:131:14)
```

**Comment by steffanhalv** [comment]
I found why;

**proxy.web target can not be set like in createProxyServer options:**

WRONG
```js
proxy.web(req, res, { target: { host: 'http://localhost', port: 8080 } }
```

CORRECT
```js
proxy.web(req, res, { target: 'http://localhost:8080' }
```

in createProxyServer you can do like this:

```js
httpProxy.createProxyServer({
  target: {
    host: 'http://localhost',
    port: 8080
  }
})
```

**Comment by chevsunpower** [comment]
Thanks for this. Helped me figure out that the cryptic error was due to an environment variable containing a URL with no protocol. Was scratching my head for quite a while at this very unhelpful error.
