### ISSUE TITLE
How to do 301 redirects

### ISSUE THREAD

**Issue by patrickroberts** [nodejitsu/node-http-proxy#1030]
I want to reopen [this issue](37) since 301 redirects still don't seem to work. Here's some reproducible code:

`index.js`:

```
var http = require('http');
var express = require('express');
var httpProxy = require('http-proxy');

var app = express();
var proxy = httpProxy.createServer();

app.get('/', function (req, res) {
  res.send('<h1>Welcome</h1>');
});

proxy.on('upgrade', function (req, socket, head) {
  proxy.ws(req, socket, head);
});

var server = http.createServer(function (req, res) {
  console.log(req.url);

  if (req.headers['host'] === process.env.HEROKU_APP_NAME + '.herokuapp.com') {
    app(req, res);
  } else {
    proxy.web(req, res, {
      target: req.url,
      protocolRewrite: true
    });
  }
});

server.listen(process.env.PORT || 8000);
```

Here was the output:

```
$ node index
http://nodejs.org/
url.js:398
  if (protocol && protocol.substr(-1) !== ':') protocol += ':';
                           ^

TypeError: protocol.substr is not a function
    at Url.format (url.js:398:28)
    at Array.setRedirectHostRewrite (/Users/patrick/Servers/open-proxy/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:70:40)
    at ClientRequest.<anonymous> (/Users/patrick/Servers/open-proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:157:20)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

For reference I'm using node 4.2.4, and http-proxy 1.14.0.

**Comment by dancingfrog** [comment]
@patrickroberts

I'm also trying to route to a 301 redirect with http-proxy and so far I'm only seeing reverse proxy behavior. Even when I look at your example, there's no parameter that would specify a 301 response (meaning that the client should be sent an endpoint url to make a new request against, similar to Express' ```res.redirect(301, redirectUrl);```).

 ```protocalRewrite: true``` has no effect on the action of the``` web({})``` method. 

Also, can you please print the request + headers that you are using because I'm not able to reproduce the ```TypeError``` exception above.

Thanks,
John

**Comment by morkeleb** [comment]
I'm hitting the same issue with 1.14.0, basically any redirect I hit the browser traffic leaves the proxy for the real site.

I'm using the following setup:

```
  var proxy = httpProxy.createProxyServer({
    target:options.url,
    autoRewrite: true,
    hostRewrite: true,
    changeOrigin: true
  }).listen(options.localProxy);
```

**Comment by apsavin** [comment]
I think #1195 should fix this issue.
