### ISSUE TITLE
Exception after 1.15.1

### ISSUE THREAD

**Issue by ducklord** [nodejitsu/node-http-proxy#1064]
Hey

We are getting this exception `The header content contains invalid characters` after the update of 1.15.1. The reason is that union's response-stream does not implement the interface you describe in the 1.15.1 patch.

```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.writeHead (node_modules/union/lib/response-stream.js:75:21)
    at Array.writeStatusCode (node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:113:11)
    at ClientRequest.<anonymous> (node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:157:20)
```

Not sure if you are willing to fix this, since this is basically unions fault. But the error is first exposed in your 1.15.1.

Best regards
Anders

**Comment by reykjavikingur** [comment]
+1
I'm seeing this in Chrome 52 running it as part of Express middleware. It happens in 1.15.1 and 1.15.2, but it is fine in 1.13.3.

**Comment by jcrugzz** [comment]
@ducklord the fix should be in union. @reykjavikingur could you post some code, a stacktrace and the version of express this is associated with?

**Comment by jcrugzz** [comment]
This should be fixed with latest union which would be installed with latest `http-server`. @reykjavikingur would love to see a test for your failure case added to this project. It doesn't seem clear to me why this would be happening with standard `express`
