### ISSUE TITLE
value required in setHeader

### ISSUE THREAD

**Issue by dynnamitt** [nodejitsu/node-http-proxy#1112]
i do not understand why i cannot modify request headers?

Ive tried 

    req.headers['x-my-header']=somestring

and even the doc sample

     proxy.on 'proxyReq', (proxyReq, req, res, options) ->
        proxyReq.setHeader 'x-my-header',somestring

but allways same error

> Error: `value` required in setHeader("X-my-header", value).
>      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:342:11)
>      at ProxyServer.<anonymous> (/app/lib/routes/proxy.js:78:20)
>      at ProxyServer.emit (/app/node_modules/http-proxy/node_modules/eventemitter3/index.js:119:35)
>      at ClientRequest.<anonymous> (/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:125:27)
>      at emitOne (events.js:82:20)
>      at ClientRequest.emit (events.js:169:7)
>      at tickOnSocket (_http_client.js:491:7)
>      at onSocketNT (_http_client.js:503:5)
>      at nextTickCallbackWith2Args (node.js:442:9)
>      at process._tickCallback (node.js:356:17)

**Comment by dynnamitt** [comment]
ok 
forgot to check somestring  ..its undef
