### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by sadovnik** [nodejitsu/node-http-proxy#1124]
```
$ node server.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at ProxyServer.listen (/var/www/app/proxy/node_modules/http-proxy/lib/http-proxy/index.js:135:16)
    at Object.<anonymous> (/var/www/app/proxy/server.js:4:58)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
$ node -v
v6.9.2
$ cat server.js
var http = require('http'),
    httpProxy = require('http-proxy');

httpProxy.createProxyServer({target:'http://localhost'}).listen(80);
```

**Comment by sadovnik** [comment]
Whoops, this is a port access issue.
