### ISSUE TITLE
tls_process_ske_dhe:dh key too small

### ISSUE THREAD

**Issue by Sevyls** [nodejitsu/node-http-proxy#1306]
Hi,

When I open a proxy server to the https URL of Cisco's Finesse Sandbox Environment, I get the following errors with node-http-proxy:

```
{ Error: write EPROTO 4438324672:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../../vendor/node/deps/openssl/openssl/ssl/statem/statem_clnt.c:1457:

    at WriteWrap.afterWrite [as oncomplete] (net.js:833:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
{ Error: write EPROTO 4438324672:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../../vendor/node/deps/openssl/openssl/ssl/statem/statem_clnt.c:1457:

    at WriteWrap.afterWrite [as oncomplete] (net.js:833:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
```  

Is there any way to deactivate DHE Ciphers with http-proxy?

**Comment by Sevyls** [comment]
Work around:
```
const httpProxy = require('http-proxy');
httpProxy.createProxyServer({
  target: {
    hostname: "hq-uccx.abc.inc", // "vm-finesse-01.notrufnoe.at",
    port: 8445,
    protocol: 'https:',
    ciphers: 'AES128-SHA', // <-- For Cisco Finesse 10.6 nothing newer than AES128-SHA only works!
    secureProtocol: 'TLSv1_method', // <-- For Cisco Finesse 10.6 nothing newer than TLS 1.0 only works!
  }
}).listen(8089, 'localhost');
