### ISSUE TITLE
WebSocket `Error: socket hang up`

### ISSUE THREAD

**Issue by danstaak** [nodejitsu/node-http-proxy#1336]
I'm trying to Proxy NodeBB into another Node.js app. I have followed and have the exact code in my 'frontend node.js app' as in this article - https://docs.nodebb.org/configuring/proxies/node/

The frontend part of the proxy works fine - browsing to **/website.co.uk/forum** loads in the forum from another URL, through this module. 

However, the websocket part does not work at all. The below error is what I get when trying to make the WebSocket calls:

```
{
    Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) code: 'ECONNRESET'
}
```

This is how I am using the module to proxy 'normal' requests vs. websocket requests:

```
...

var proxyRules = new HttpProxyRules({
    rules: {
        '.*/forum': 'http://myforum.co.uk/forum', // Rule (2) forums
        '.*/forum/*': 'http://myforum.co.uk/forum', 
        '/forum/*': 'http://myforum.co.uk/forum',
        './forum/*': 'http://myforum.co.uk/forum',
        '/forum': 'http://myforum.co.uk/forum' 
    },
    default: 'http://localhost:8081' // load default frontend app served on another URL
});

var proxy = httpProxy.createProxy();

var express = require('express');
var bodyParser = require('body-parser')
var mainapp = express();
mainapp.use(function(req,res,next){
    try{
        if (req.url.substr(0, 18).indexOf("socket.io")>-1){
            //console.log("SOCKET.IO", req.url)
            return proxy.web(req, res, {
                target: 'wss://myforum.co.uk',
                ws: true
            }, function(e) { 
            //console.log('PROXY ERR',e)
            });
        } else {
            var target = proxyRules.match(req);
            if (target) {
                //console.log("TARGET", target, req.url)
                return proxy.web(req, res, {
                    target: target,
                    changeOrigin: true
                }, function(e) { 
                //console.log('PROXY ERR',e)
                });
            } else {
                res.sendStatus(404);
            }
        }
    } catch(e){
        res.sendStatus(500);
    }
});
mainapp.use(bodyParser.json());
mainapp.use(bodyParser.urlencoded({ extended: false }));

...
```

**Comment by forvino** [comment]
seems this is reoccurring causing stability in production ...is there any ETA if this is prioritized at all? or work around ?

**Comment by guguji5** [comment]
I move the `app.use(bodyParser())` after the proxy middleware just like below 

```
// middleware
app.use(proxy('/flow', {
  target: 'http://example.com',    
  changeOrigin: true,
  rewrite: path => {
    return path.replace('/dicloud/feapi/','/')
  },
  logs: true
}))

app.use(bodyParser()) // must behind the proxy
```

and fix it.
