### ISSUE TITLE
Issue using proxy.ws

### ISSUE THREAD

**Issue by umb-hub** [nodejitsu/node-http-proxy#1465]
I wanted proxying only WebSocket traffic, so i used proxy.ws as shown in comment in [documentation](https://github.com/http-party/node-http-proxy#setup-a-stand-alone-proxy-server-with-custom-server-logic), but i got this error.

Error on open WebSocket on proxy:

```
/home/toor/proj/server/node_modules/http-proxy/lib/http-proxy/common.js:129
  socket.setKeepAlive(true, 0);
         ^

TypeError: socket.setKeepAlive is not a function
    at Object.common.setupSocket (/home/toor/proj/server/node_modules/http-proxy/lib/http-proxy/common.js:129:10)
    at Array.stream (/home/toor/proj/server/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:98:12)
    at ProxyServer.<anonymous> (/home/toor/proj/server/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at Server.<anonymous> (/home/toor/proj/server/test.js:22:11)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:691:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)

```

Node Version:
`v10.21.0
`

Depedencies:
```
"http": "0.0.1-security",
"http-proxy": "^1.18.1",
"ws": "^7.3.1"
```

test.js:
```
var http = require('http');
var httpProxy = require('http-proxy');
var WebSocketServer = require('ws').Server;

var wss = new WebSocketServer({ port: 3002 });

wss.on('connection', function connection(ws) {
   console.log("OK")
});

var proxy = httpProxy.createServer({ 
	target: 
	{
		host: 'localhost',
		port: 3002
	},
	ws:true
});


var server = http.createServer(function(req, res) {
    proxy.ws(req,res)
}).listen(3001);
```

All working fine using `proxy.web(req,res)` instead of `proxy.ws(req,res)`.

**Comment by umb-hub** [comment]
Solved:
`proxy.ws(req,req.socket,req.headers)
