### ISSUE TITLE
Dynamic target (server) with POST parameter

### ISSUE THREAD

**Issue by Tokscull** [nodejitsu/node-http-proxy#1512]
I want to choose target by using POST parameters. I wrote below code.

```
const http = require('http');
const httpProxy = require('http-proxy');

const getRawBody = (req) => {
    let rawBody = '';
    return new Promise((resolve, reject) => {
        req.setEncoding('utf8');
        req.on('data', chunk => rawBody += chunk);
        req.on('end', () => resolve(rawBody));
        req.on('error', err => reject(err));
    });
}

const pickOneServer = async (req) => {
    req.rawBody = await getRawBody(req);
    //custom logic to verify request and choose the right server using request headers and raw body (not parsed)
    //line below just for example 
    return 'localhost:3001';
}

const proxy = httpProxy.createProxyServer();
http.createServer((req, res) => {
    pickOneServer(req).then(server => {
        console.log(server);
        proxy.web(req, res, {
            target: `http://${server}`,
        });
    });
}).listen(3001, () => logger.default.info(`SLACK PROXY: Listening on 3001...`));
```
And I get the next error:
```
BadRequestError: request aborted
    at IncomingMessage.onAborted ('myAppDirectory'\node_modules\body-parser\node_modules\raw-body\index.js:231:10)
    at IncomingMessage.emit (events.js:311:20)
    at abortIncoming (_http_server.js:532:9)
    at socketOnClose (_http_server.js:525:3)
    at Socket.emit (events.js:323:22)
    at TCP.<anonymous> (net.js:668:12)
```

There any way to make it?

**Comment by ghuser** [comment]
@Tokscull How did you achieve the above finally?

**Comment by Tokscull** [comment]
@ghuser You can do it like this:

```
const pickOneServer = async (req) => {
   //custom logic; line below just for example 
   return 'localhost:3001';
};


const proxy = httpProxy.createProxyServer();

proxy.on('proxyReq', (proxyReq, req, res, options) => {
   if (req.body) {
     // let bodyData = JSON.stringify(req.body);
     let bodyData = req.rawBody;
     // proxyReq.setHeader('Content-Type', 'application/json');
     proxyReq.setHeader('Content-Type', 'application/x-www-form-urlencoded');
     proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));

     proxyReq.write(bodyData);
   }
});


const app = express();

const rawBodyBuffer = (req, res, buf, encoding) => {
   if (buf && buf.length) {
     req.rawBody = buf.toString(encoding || 'utf8');
   }
};

app.use(bodyParser.json({ verify: rawBodyBuffer }));
app.use(bodyParser.urlencoded({ verify: rawBodyBuffer, extended: true }));

app.use((req, res) => {
   pickOneServer(req).then(server => {
     if (server) {
       proxy.web(req, res, {
         target: `http://${server}`,
         secure: false,
       });
     } else {
       res.status(403).send('Signature mismatch.');
     }
   });
});
http.createServer(app).listen(port, () => logger.default.info(`Listening on ${port}...`));
```

**Comment by capaj** [comment]
@Tokscull  You'd think they would put this in the docs somewhere.
