### ISSUE TITLE
988 char long access token caused `SyntaxError: Unexpected token ▼ in JSON at position 0 ...` for JSON.parse() in proxyRes

### ISSUE THREAD

**Issue by yelnyafacee** [nodejitsu/node-http-proxy#1514]
I got this `Nextjs` `API` that returns:
```
res.status(200).json({ result: result })
```
and result is:
```
const result = {
"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9",
'expiry_date': 123132
}
```

and I am intercepting the response with:

```
        function interceptLoginResponse(proxyRes, req, res) {

            // Read the API's response body from
            // the stream:
            let apiResponseBody = []

            proxyRes.on('data', (chunk) => {
                // apiResponseBody += chunk
                apiResponseBody.push(chunk);
            })

            // Once we've read the entire API
            // response body, we're ready to
            // handle it:
            proxyRes.on('end', () => {

                try {

                    apiResponseBody = Buffer.concat(apiResponseBody).toString();

                    // Extract the authToken from API's response:
                    const { result } = JSON.parse(apiResponseBody)

                    console.log("authToken: ", result);

                    // Set the authToken as an HTTP-only cookie.
                    // We'll also set the SameSite attribute to
                    // 'lax' for some additional CSRF protection.
                    const cookies = new Cookies(req, res)

                    cookies.set('auth-token', result, {
                        httpOnly: true,
                        sameSite: 'lax'
                    })

                    // Our response to the client won't contain
                    // the actual authToken. This way the auth token
                    // never gets exposed to the client.
                    res.status(200).json({ loggedIn: true })

                    resolve()

                } catch (err) {

                    reject(err)

                }

            })
        }
```

the above code works because I am using the `"access_token"` value of `"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9"`
but when I replace it with the REAL `access_token` (`eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiM2VmOGQyNWI5MWQ5ZGNiNzMyMjk0MGI0ZDc0NmI5MjBkMGI1MWMxMTI3YzM4YmM4OTg3YWUyMGY4MjVmZTA3ZDExNDEzOWRmZWZiYWU1NzciLCJpYXQiOiIxNjE4ODk2MzA3Ljg4MDgyNiIsIm5iZiI6IjE2MTg4OTYzMDcuODgwODI5IiwiZXhwIjoiMTY1MDQzMjMwNy44MzgyNDIiLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.tyEV3_MbzLMR0oySeQwgwrc9kHjrvLLhO0cJhWO_u6_5MNe3DpxABWigzH02jhvBiqgz8qSulPMNI9jI4jmGsq6i5Fptv0gwnmD_DlvOaexgm7zOWy6Ui7HUCq6a9Lz1eXKOU-HCbkdYk2zmnQKMZLS9Zu3-STeIBT9u8vuQRPZmpJ6rySUT7apfANW14CvGJf2x-L2nIY5brz5UeYHqYmcRciknghsQEyI5iw-rfTxkhW7pQeOFhGPyHR-iZuYCRV8SuDS_HKspEEIXyEp3jxkVeG3NBAp3tnFCtE9kmP4JxCkY-bUhco_FmNWSlXw1ealst-6u3E_ZW923fGATNoIW1MV5MbVpPOR74tF87IJeGAX3P7sXrQs6bLQ3doR91EMnSm9cKZToNL2IoV3wyZHUqFPoUVkNcBPxZCzN67JbdvnVoaLnLfBjiGZQonsaUurEcZJs1FRXhZCXAd_TJlI1qUCKDq4h1g8yV2lajJs55dNGTFAYx3aS5PvWJxwUMhlCQzvOkYTJhiCOH-MhQXRz9e7ruBQphxRuogFO4CcbMdEksiGhzMnPdUKLxq88tKJ2L-cR_igESjlHsa330aIgu-GST9Jk4CmGLLkpnZAmh0lJqAYn9_ftinEHs3J7SLPpET5FtIj-mp4otOzdCLbmGZRMfiZF4wZd8yafSXw`) [ 988 character long ]

the `JSON.parse()` fails with the Error:
```
SyntaxError: Unexpected token ▼ in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\xampp\htdocs\lounge-react\.next\server\pages\api\proxy\[...path].js:199:20)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

How do I fix this?

**Comment by ckrithub** [comment]
Hi @yelnyaface. How did you fix this?

Today I had a similar problem with an account creation route, but I noticed that's not happen when API responses an error status (422). For now, my workaround was changing the API's response from 200 to 201.

This happened only in production. I need to investigate further. I'm running the API under Cloudflare, maybe it's an additional header information.
