### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by trusktr** [nodejitsu/node-http-proxy#527]
I'm getting errors that look like this happening every hour or two, causing systemd to restart my nodeProxyServer.js script:

```
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: throw arguments[1]; // Unhandled 'error' event
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: ^
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: Error: socket hang up
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at createHangUpError (http.js:1360:15)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at ServerResponse.OutgoingMessage._writeRaw (http.js:507:26)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at ServerResponse.OutgoingMessage._send (http.js:476:15)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at ServerResponse.OutgoingMessage.write (http.js:740:18)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at ClientRequest.proxyError (/srv/nodeProxyServer/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:211:13)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at ClientRequest.g (events.js:192:14)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at ClientRequest.EventEmitter.emit (events.js:96:17)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at Socket.socketCloseListener (http.js:1411:9)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at Socket.EventEmitter.emit (events.js:126:20)
Nov 10 16:49:17 fountainsunique nodeProxyServer[24009]: at Socket._destroy.destroyed (net.js:358:10)
Nov 10 16:49:17 fountainsunique nodeProxyServer[27651]: Proxy server started on port 80.
Nov 10 16:51:17 fountainsunique nodeProxyServer[27651]: res.end error: socket hang up
```

May it be related to node-http-proxy, or something else?

**Comment by bitliner** [comment]
Same problem here: ` Error { [Error: socket hang up] code: 'ECONNRESET' }`.

The cose is: 

```
app.post('/export/bis', function(req, res) {

		proxy.web(req, res, {
			target: 'http://localhost:40010/export/bis',
		});
	});
```

**Comment by NightFury2** [comment]
`
const targetUrl = config.apiHost + config.apiPort;
const proxy = httpProxy.createProxyServer({
  target: targetUrl
});
// Proxy to API server
app.use('/api', (req, res) => {
  console.log(req.originalUrl);
  console.log(targetUrl);
  proxy.web(req, res, {target: targetUrl});
});`

Why http proxy send a request to the right address, and receives 404, and if you open the same address through brouser gets json.
checked through console.log the issue the required address
