### ISSUE TITLE
Proxying websockets with single "proxyServer" to multiple targets. [caronte]

### ISSUE THREAD

**Issue by Rush** [nodejitsu/node-http-proxy#533]
The casual example shows proxying web sockets when target was provided to the `createProxyServer` function, however when dispatching http requests I want only a single proxyServer instance per port.

I wrote a simple test and a WebSocket enabled website running at port 4000:

```
var httpProxy = require('http-proxy'), http = require('http');
var proxy = new httpProxy.createProxyServer({});
var proxyServer = http.createServer(function (req, res) {
 // dispatching to different targets would happen here
  proxy.web(req, res,  {target: {
    host: 'localhost',
    port: 4000
  }});
});
proxyServer.on('upgrade', function (req, socket, head) {
  proxy.ws(req, socket, head);
});
proxyServer.listen(4080);
```

However, this does not work and errors out with:

```
TypeError: Cannot read property 'protocol' of undefined
    at Array.stream rush-http-proxy/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:87:63)
```

Adding a simple workaround by bassing `{target: {protocol: 'http'}}' yields:

```
{ [Error: socket hang up] code: 'ECONNRESET' }

server.emit('error', err, req, socket);
               ^
TypeError: Object [object Object] has no method 'emit'
    at ClientRequest.onError (rush-http-proxy/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:114:16)
```

How can we fix it?

**Comment by manjeet13** [comment]
How can I have multiple targets? target property only takes a string right? Setting it to a list of targets doesn't seem to be doing the trick.
