### ISSUE TITLE
Dynamic load balancing with POST parameter

### ISSUE THREAD

**Issue by Lewuathe** [nodejitsu/node-http-proxy#628]
I want to load balance by using POST parameters. I wrote below code.

``` js
var httpProxy = require('http-proxy');                                                                                                                                            
var proxy = httpProxy.createServer({});

var server = require('http').createServer(function(req, res) {
    var data = '';                                                                                                                                                                
    req.on('data', function(chunk) {                                                                                                                                              
        data += chunk;                                                                                                                                                            
    });                                                                                                                                                                           
    req.on('end', function() {                                                                                                                                                    
        var host = /=(.+)$/.exec(data)[1];                                                                                                                                                console.log(host);                                                                                                                                                        
        proxy.web(req, res, {                                                                                                                                                     
            target: 'http://' + host,                                                                                                                                             
            ws: true,                                                                                                                                                
        });                                                                                                                                                                       
    });                                                                                                                                                                           
});

console.log('Starting server...');
server.listen(8080);
```

Request is this.

```
$ curl -X POST localhost:8080 -d "target=google.com"
```

However, this didn't work I expected. I cannot get response from target server. I think that `req` has already received `end` event in this proxy server. So in the target server(in this case `google.com`) `end` event is never emitted. I use this alternative.

``` js
var httpProxy = require('http-proxy');
var proxy = httpProxy.createServer({});

var server = require('http').createServer(function(req, res) {                                                                                                                                                                          
    var host = req.headers['target'];                                                                                                                                             
    proxy.web(req, res, {                                                                                                                                                         
        target: 'http://' + host,                                                                                                                                                 
        ws: true                                                                                                                                                                  
    }); 
});

console.log('Starting server...');
server.listen(8080);
```

And request.

```
$ curl -X POST localhost:8080 -H "target: google.com"
```

If it is needed just to read `headers`, `end` event will not be emitted in the proxy server. This alternative works properly.
But is there any way to load balance with POST parameter dynamically?

node version is 0.10.26 and http-proxy module version is 1.1.2.

```
$ node -v
v0.10.26
```

**Comment by macscripter** [comment]
Hi, I have exactly the same problem..... How to sort it out? in my case I need to call a host dependindg ot the miTag:


var http = require('http'),
httpProxy = require('http-proxy'),
proxy = httpProxy.createProxyServer({});

var miTarget='web:CountryName';
var inicio = '<'+miTarget+'>';
var fin = '</'+miTarget+'>';

var server = http.createServer(function(req, res) {
var miTag = '';
req.on('data', function (data) { 
miTag = data.toString().split(inicio)[1].split(fin)[0];
});

  req.on('end', function () {
  console.log('miTag!!!!!!:'+miTag);
  if(miTag=='Portugal') {
  proxy.web(req, res, {target: 'http://www.webservicex.net'}); 
  }
  else { 
  proxy.web(req, res, {target: 'http://localhost:1337'}); 
  }

  });    
});

console.log("listening on port 80")
server.listen(80);

**Comment by macscripter** [comment]
Waw, I have exctly the same problem that doesn't make me relaxed this weekend.... Can someone clarify how to resolve it? Here goes my code:

var http = require('http'),
httpProxy = require('http-proxy'),
proxy = httpProxy.createProxyServer({});

var miTarget='web:CountryName';
var inicio = '<'+miTarget+'>';
var fin = '</'+miTarget+'>';

var server = http.createServer(function(req, res) {
var miTag = '';
req.on('data', function (data) { 
miTag = data.toString().split(inicio)[1].split(fin)[0];
});

  req.on('end', function () {
  console.log('miTag!!!!!!:'+miTag);
  if(miTag=='Portugal') {
  proxy.web(req, res, {target: 'http://www.webservicex.net'}); 
  }
  else { 
  proxy.web(req, res, {target: 'http://localhost:1337'}); 
  }

  });    
});

console.log("listening on port 80")
server.listen(80);

**Comment by Lewuathe** [comment]
@macscripter As I described before, I passed my routing parameter on HTTP header, not POST parameter. Even end event is emitted on proxy server side, we can read the items in HTTP header. 
This was the solution that I took. 
But I don't know whether latest node-http-proxy could resolve this issue or not even in POST parameter. So please check it.

Thank you.

**Comment by macscripter** [comment]
Thank you!
I understand this solution but I could not change the request from my
front, so I really need to get the parameter from the POST using the
req.on('data') or req.on('end') envent.
Anyway, I really appreciate your feedback regarding to this issue.

Thank you!

Warmest regards

2015-11-16 0:17 GMT+00:00 Kai Sasaki <notifications@github.com>:

**Comment by Tokscull** [comment]
Any updates in this question?
I have the same problems as @macscripter. I need to get  parameter from the POST using the
req.on('data') for choosing right server address.

My code:
```
    const http = require('http');
    const httpProxy = require('http-proxy');

    const proxy = httpProxy.createProxyServer();
    http.createServer((req, res) => {
        let rawBody = '';
        req.on('data',(data) =>{
            rawBody += data;
        });
        req.on('end', () => {
            let server = pickOneServer(req, rawBody);
            proxy.web(req, res , {
                target: `http://${server}`,
            })
        });
    }).listen(3001, () => logger.default.info(`SLACK PROXY: Listening on 3001...`));
```
And I get the next error: 
`BadRequestError: request aborted
    at IncomingMessage.onAborted ('_myAppDirectory_'\node_modules\body-parser\node_modules\raw-body\index.js:231:10)
    at IncomingMessage.emit (events.js:311:20)
    at abortIncoming (_http_server.js:532:9)
    at socketOnClose (_http_server.js:525:3)
    at Socket.emit (events.js:323:22)
    at TCP.<anonymous> (net.js:668:12)
`
