### ISSUE TITLE
HTTP-> HTTP : Transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by fosstrack** [nodejitsu/node-http-proxy#641]
OS: Mac OSX 10.8
Node.js: v0.10.28
node-http-proxy: HEAD / 1.1.3

HTTP -> HTTP Proxying to a certain api server throws the following error:
/Users/.../node-http-proxy/lib/http-proxy/index.js:114
    throw err;
          ^
Error: Parse Error
    at Socket.socketOnData (http.js:1583:20)
    at TCP.onread (net.js:527:27)

The JSON data is dumped properly, but the proxy server crashes before closing the connection.  How do I debug this?

**Comment by andreyrd** [comment]
Running into the same issue in 2018, 4 years later...
