### ISSUE TITLE
PUT / POST requests broken in node 0.12.0

### ISSUE THREAD

**Issue by billmccord** [nodejitsu/node-http-proxy#777]
When I upgraded to node v0.12.0, performing proxied PUT / POST requests gave errors like this:
node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:413:15)
    at IncomingMessage.ondata (_stream_readable.js:540:20)
    at IncomingMessage.emit (events.js:107:17)
    at /Users/bill/Source/LN/impactscore_client/node_modules/connect-restreamer/index.js:15:13
    at process._tickCallback (node.js:355:11)

Rolling back to node v0.10.36, everything is working fine.

**Comment by diimdeep** [comment]
Same here, from atom-shell, i think same node version

```
Uncaught Exception:
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:415:15)
    at Socket.proxyError (/Users/wolf/hello-atom/node_modules/ipython-notebook-proxy/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:204:13)
    at Socket.g (events.js:202:16)
    at Socket.emit (events.js:138:20)
    at net.js:452:14
    at process._tickDomainCallback (node.js:392:11)
```

**Comment by shlomihassan** [comment]
hi guys,

i having the same problem 
have you managed to solve the problem ?

**Comment by jcrugzz** [comment]
I'd love to have a failing test case added in tests so we can get this resolved.

**Comment by leejefon** [comment]
I had the same problem with connect-restreamer.  I found a fix ([https://github.com/dominictarr/connect-restreamer/issues/8]).  Not the best solution, but it works for me :)

**Comment by trustmaster** [comment]
I came across the same error message in code not using `node-http-proxy`. Not sure if this helps you guys, but what caused this bug in my case was `http.get` being used instead of `http.request` for POST requests. Seems like it was an alias in Node 0.10 but the behavior changed in 0.12. Replacing `http.get` with `http.request` fixed it for me.
