### ISSUE TITLE
Configure proxy server help

### ISSUE THREAD

**Issue by emmenko** [nodejitsu/node-http-proxy#811]
Hi, I'm trying to get the proxy server to work but I'm having some troubles.

So just for testing, I have this little proxy server setup.

```js
import http from 'http'
import httpProxy from 'http-proxy'

const host = 'api.github.com'
const protocol = 'https'
const proxy = httpProxy.createProxyServer({
  target: { host, protocol }
})

const server = http.createServer(function () {
  proxy.web(...arguments)
})

console.log('listening on port 5050')
server.listen(5050)
```

So pretty straightforward. What I would expect here is if I call `http://localhost:5050` I would get proxied to `https://api.github.com`.

```bash
$ curl -vL http://localhost:5050
* Rebuilt URL to: http://localhost:5050/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5050 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:5050
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

And the server crashes with:

```bash
listening on port 5050

node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at Socket.socketOnEnd [as onend] (http.js:1572:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

Now, if I try with 

```js
const host = 'google.com'
const protocol = 'http'
```

I correctly get proxied to `google.com`, but if I try with

```js
const host = 'google.com'
const protocol = 'https'
```

it doesn't

```bash
$ curl -vL http://localhost:5050
* Rebuilt URL to: http://localhost:5050/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5050 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:5050
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

and server crashes with

```bash
listening on port 5050

node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

Any idea what's going on or what am I doing wrong?
Thanks

**Comment by emmenko** [comment]
Ok, I actually made it work if I pass the target when I proxy the request instead of when I create the proxy server.

```js
// problems
const proxy = httpProxy.createProxyServer({
  target: { host, protocol }
})
...
proxy.web(...arguments)

// works
const proxy = httpProxy.createProxyServer()
proxy.web(request, response, { target: 'https://api.github.com' })
```
