### ISSUE TITLE
Error: socket hang up at createHangUpError (http.js:1477:15) with node 0.10.34

### ISSUE THREAD

**Issue by my541619352** [nodejitsu/node-http-proxy#824]
I get the following error when I use http-proxy .
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketOnEnd [as onend] (http.js:1573:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
thanks

**Comment by my541619352** [comment]
fixed. found solution in 
hanging POST requests #180
