### ISSUE TITLE
proxy localhost without internet connection gives "getaddrinfo ENOENT"

### ISSUE THREAD

**Issue by flyon** [nodejitsu/node-http-proxy#835]
I've got node running on http://localhost:8001 and have http-proxy configured to proxy https://localhost:8002 back to http://localhost:8001.

This works fine as long as I'm connected to the internet, but when I'm disconnected from the internet http://localhost:8001 still works, but when I access https://localhost:8002 I get this error:

```F:\wamp\www\sendsteps\nodejs\node_modules\http-proxy\lib\http-proxy\index.js:119
    throw err;
          ^
Error: getaddrinfo ENOENT
    at Object.exports._errnoException (util.js:746:11)
    at errnoException (dns.js:49:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)```

Which makes it hard for me to work with this while on the road.

Is there some setting I should set or should it be fixed?

**Comment by peterhodges** [comment]
I ran into this yesterday.

Try using 127.0.0.1 instead of localhost.

See: https://github.com/nodejs/node-v0.x-archive/issues/25338
