### ISSUE TITLE
benchmark failed when using more threads

### ISSUE THREAD

**Issue by tyrchen** [nodejitsu/node-http-proxy#873]
When I use 100 connections with 8 threads:

➜  node-http-proxy git:(master) ✗ wrk -c 100 -d1m -t 8 http://127.0.0.1:8000

The proxy server will quit after a while:

➜  node-http-proxy git:(master) ✗ node benchmark/scripts/proxy.js
/Users/tchen/projects/startup/study/node-http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

Probably the proxy.js shall silently drop the errors to let the benchmark finish.

**Comment by kar1m** [comment]
I hit the same issue when benchmarking http-proxy. Does anyone know if the same will happen in a real life production environment with a high request volume or if this issue is tied to the fact that the connections are created from the same client?
I tested with nginx and the npm module 'loadbalancer', no problem there.

@tyrchen @jcrugzz
