### ISSUE TITLE
Error: "name" and "value" are required for setHeader().

### ISSUE THREAD

**Issue by ro31337** [nodejitsu/node-http-proxy#876]
Time to time I'm getting this error, no clear steps to reproduce:

	_http_outgoing.js:333
		throw new Error('"name" and "value" are required for setHeader().');
	Error: "name" and "value" are required for setHeader().
	  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
	  at C:\work\hlproxy\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:85:11
	  at Array.forEach (native)
	  at Array.writeHeaders (C:\work\hlproxy\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:84:35)
	  at ClientRequest.<anonymous> (C:\work\hlproxy\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:149:20)
	  at ClientRequest.emit (events.js:107:17)
	  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
	  at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
	  at Socket.socketOnData (_http_client.js:317:20)
	  at Socket.emit (events.js:107:17)
	  at readableAddChunk (_stream_readable.js:163:16)
	  at Socket.Readable.push (_stream_readable.js:126:10)
	  at TCP.onread (net.js:538:20)

**Comment by ro31337** [comment]
For temp workaround I modified writeHeaders function to

	  function writeHeaders(req, res, proxyRes) {
		Object.keys(proxyRes.headers).forEach(function(key) {
		  if(proxyRes.headers[key]) { // <-- fixed here
			res.setHeader(key, proxyRes.headers[key]);
		  }
		});
	  },

**Comment by jcrugzz** [comment]
@ro31337 interesting, im curious as to what header caused this type of error? Could you `console.dir(proxyRes.headers)` for me?

**Comment by ro31337** [comment]
@jcrugzz I'll try, but it's hard to catch. I'll modify my code to catch that, and we'll wait

**Comment by VarunBatraIT** [comment]
Once I updated to node 4, I started to look at this error. It wasn't there before.

**Comment by jcrugzz** [comment]
@VarunBatraIT will start testing on `node 4`, I'd love to have a PR for a failing test case though if one doesn't exist already. Thanks for the heads up
