### ISSUE TITLE
[Error: socket hang up]

### ISSUE THREAD

**Issue by PanYuntao** [nodejitsu/node-http-proxy#923]
Hi~

I get error when run the post data to gateway, the problem is that proxy work excellent in case of get requests but in case of post requests it results in socket hang up exception ,no post body is ok!

```
{ [Error: socket hang up] code: 'ECONNRESET' }
Error: request aborted
    at IncomingMessage.onAborted (/Users/flat_peach/Downloads/strong-gateway-demo-master/oauth-playground/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.serverSocketCloseListener (_http_server.js:293:5)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by futurist** [comment]
also I have similar error, but not related to `POST` data
Here if user redirect frequently, e.g. click back button frequently in a 302 redirected page, error below:
````
/root/node-proxy/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: socket hang up
    at createHangUpError (_http_client.js:209:15)
    at Socket.socketCloseListener (_http_client.js:241:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
````

**Comment by PanYuntao** [comment]
@yjm  Thanks for your help. I find the problem that I add body parser  js
file  in `ROOT` folder. :(

2015-12-31 17:29 GMT+08:00 yjm <notifications@github.com>:

**Comment by guguji5** [comment]
@PanYuntao  so you fix it ？ by adding body parser js file in ROOT folder.

what's that mean ?
