### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by xolf** [nodejitsu/node-http-proxy#930]
I just got a very strange error. The proxy tries to send the header twice and I have no idea why.

```
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at g:\nodejs\http-proxy\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:85:11
    at Array.forEach (native)
    at Array.writeHeaders (g:\nodejs\http-proxy\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:84:35)
    at ClientRequest.<anonymous> (g:\nodejs\http-proxy\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:151:20)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:310:20)
    at Socket.emit (events.js:107:17)
```

My `proxy.js` file: https://gist.github.com/xolf/f79a1f939d7dc64c9894

**Comment by adambiggs** [comment]
+1 I'm having the same problem.

**Comment by pyper** [comment]
This situation happens when request() call throws an error.  It looks like you have a race condition between your response error function and the web proxy.  What is happening is the request() call is failing and the custom error handler and the proxy are fighting over the same response object.  res.headersSent will not provide you protection because after both times you use them there is many asynchronous callbacks past them.   The stack trace I am getting is indicating the error is originating in the proxy which mean the header flush was likely triggered by res.end() on line 31.  This f’d up the proxy since it can no longer write headers itself because the headers were sent there.  You have to rethink the fundamental structure of this app to account for the for asynchronous nature of node and http-proxy.

**Comment by jasonniebauer** [comment]
+1 I'm having the same problem

**Comment by xolf** [comment]
Is there a way to ignore this error and force the server keep on running?

**Comment by bubenshchykov** [comment]
+1

**Comment by gabrielmancini** [comment]
+1
